version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python accounts.py'
    restart: on-failure
    ports:
      - "8001:5000"
    volumes:
      - .:/accounts
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "accounts"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "54321:5432"
