version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python accounts.py'
    restart: on-failure
    ports:
      - "8001:5000"
    volumes:
      - .:/accounts
    depends_on:
      - db

  db:
    image: postgres:13.3
    env_file:
      - .env.docker
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "54321:5432"
