"""empty message

Revision ID: 0fb69470d652
Revises: 
Create Date: 2022-08-05 20:27:51.339058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb69470d652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('IBAN', sa.String(length=34), nullable=False),
    sa.Column('currency', sa.Enum('BYN', 'USD', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('IBAN')
    )
    op.create_table('customer',
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('passport_number', sa.String(length=9), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('passport_number')
    )
    op.create_table('association_bank_account_customer',
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('bank_account_id', sa.String(length=34), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.IBAN'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'bank_account_id')
    )
    op.create_table('bank_card',
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('_pin_hash', sa.String(length=256), nullable=True),
    sa.Column('_cvv_hash', sa.String(length=256), nullable=True),
    sa.Column('bank_account_iban', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_iban'], ['bank_account.IBAN'], ),
    sa.PrimaryKeyConstraint('card_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_card')
    op.drop_table('association_bank_account_customer')
    op.drop_table('customer')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
