"""add bank card

Revision ID: 9872a758a526
Revises: 98bb5c09086f
Create Date: 2022-07-17 19:48:30.427505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9872a758a526'
down_revision = '98bb5c09086f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_card',
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('CVV', sa.Integer(), nullable=False),
    sa.Column('_pin_hash', sa.String(length=256), nullable=True),
    sa.Column('bank_account_iban', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_iban'], ['bank_account.IBAN'], ),
    sa.PrimaryKeyConstraint('card_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_card')
    # ### end Alembic commands ###
