"""initial

Revision ID: 98bb5c09086f
Revises: 
Create Date: 2022-07-17 19:45:21.157575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bb5c09086f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('IBAN', sa.String(length=34), nullable=False),
    sa.Column('currency', sa.Enum('BYN', 'USD', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('IBAN')
    )
    op.create_table('customer',
    sa.Column('uuid', sa.String(length=40), server_default='2a7f4b78-670e-4507-979d-c5e40bfccb51', nullable=False),
    sa.Column('passport_number', sa.String(length=9), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('passport_number')
    )
    op.create_table('bank_accounts',
    sa.Column('customer_id', sa.String(length=9), nullable=False),
    sa.Column('bank_account_id', sa.String(length=34), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.IBAN'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.uuid'], ),
    sa.PrimaryKeyConstraint('customer_id', 'bank_account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    op.drop_table('customer')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
