"""bank card fk rename

Revision ID: a6d3dfcf2ccf
Revises: c0650fb2ceb1
Create Date: 2022-07-11 15:43:19.314699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d3dfcf2ccf'
down_revision = 'c0650fb2ceb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_card', sa.Column('bank_account_iban', sa.String(), nullable=True))
    op.drop_constraint('bank_card_bank_account_id_fkey', 'bank_card', type_='foreignkey')
    op.create_foreign_key(None, 'bank_card', 'bank_account', ['bank_account_iban'], ['IBAN'])
    op.drop_column('bank_card', 'bank_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_card', sa.Column('bank_account_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bank_card', type_='foreignkey')
    op.create_foreign_key('bank_card_bank_account_id_fkey', 'bank_card', 'bank_account', ['bank_account_id'], ['IBAN'])
    op.drop_column('bank_card', 'bank_account_iban')
    # ### end Alembic commands ###
