"""create tables

Revision ID: b04b03291366
Revises: 
Create Date: 2022-07-11 15:35:59.631393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04b03291366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('IBAN', sa.String(length=18), nullable=False),
    sa.Column('currency', sa.Enum('BYN', 'USD', 'EUR', name='currencyenum'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('IBAN')
    )
    op.create_table('bank_card',
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('CVV', sa.Integer(), nullable=False),
    sa.Column('_pin_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_table('customer',
    sa.Column('passport_number', sa.String(length=9), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('passport_number')
    )
    op.create_table('bank_accounts',
    sa.Column('customer_id', sa.String(length=9), nullable=False),
    sa.Column('bank_account_id', sa.String(length=18), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.IBAN'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.passport_number'], ),
    sa.PrimaryKeyConstraint('customer_id', 'bank_account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    op.drop_table('customer')
    op.drop_table('bank_card')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
