"""bank card

Revision ID: c0650fb2ceb1
Revises: b04b03291366
Create Date: 2022-07-11 15:42:57.254718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0650fb2ceb1'
down_revision = 'b04b03291366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_card', sa.Column('bank_account_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'bank_card', 'bank_account', ['bank_account_id'], ['IBAN'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_card', type_='foreignkey')
    op.drop_column('bank_card', 'bank_account_id')
    # ### end Alembic commands ###
