"""expand iban

Revision ID: df5dc6b62245
Revises: a6d3dfcf2ccf
Create Date: 2022-07-11 17:55:22.492317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5dc6b62245'
down_revision = 'a6d3dfcf2ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_account', 'IBAN',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=34),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'bank_account_id',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=34),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'bank_account_id',
               existing_type=sa.String(length=34),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    op.alter_column('bank_account', 'IBAN',
               existing_type=sa.String(length=34),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    # ### end Alembic commands ###
